# データベース更新エラーの取得

データベース更新時にエラーが出ると`例外がスローされました'System.Data.Entity.Validation.DbEntityValidationException'`と出るが、エラーの内容がわからないことがある。

```c#
try {
    db.SaveChanges();
} catch (DbEntityValidationException ex) {
    foreach (var entityValidationErrors in ex.EntityValidationErrors) {
        foreach (var validationError in entityValidationErrors.ValidationErrors) {
        Console.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
        }
    }
}
```

上記でエラーメッセージがコンソールに表示される

### 参考

[System\.Data\.Entity\.Validation\.DbEntityValidationExceptionを処理する方法？](https://entityframework.net/ja/knowledge-base/21606454/)